ALTER TABLE public.clientes
  ALTER COLUMN sobrenome DROP NOT NULL,
  ALTER COLUMN email DROP NOT NULL,
  ALTER COLUMN telefone DROP NOT NULL,
  ALTER COLUMN data_nascimento DROP NOT NULL,
  ALTER COLUMN cpf DROP NOT NULL;