
create table if not exists public.regras_tarifas (
  id bigint generated by default as identity primary key,
  cia text not null,
  tipo_tarifa text not null,
  regras jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.regras_tarifas enable row level security;

create policy "Enable read access for all users"
on public.regras_tarifas for select
using (true);

-- Insert initial data
insert into public.regras_tarifas (cia, tipo_tarifa, regras) values
('GOL', 'LIGHT', '{"bagagem_mao": "10kg", "bagagem_despachada": "Não inclusa", "marcacao_assento": "Paga", "alteracao": "Permitida com taxa", "cancelamento": "Não reembolsável", "no_show": "Sem reembolso"}'),
('GOL', 'PLUS', '{"bagagem_mao": "10kg", "bagagem_despachada": "1 volume de 23kg", "marcacao_assento": "Gratuita", "alteracao": "Sem taxa", "cancelamento": "Reembolsável 95%", "no_show": "Reembolsável"}'),
('GOL', 'MAX', '{"bagagem_mao": "10kg", "bagagem_despachada": "2 volumes de 23kg", "marcacao_assento": "Gratuita + Assento GOL+ Conforto", "alteracao": "Sem taxa", "cancelamento": "Reembolsável 95%", "no_show": "Reembolsável"}'),
('GOL', 'PREMIUM', '{"bagagem_mao": "10kg", "bagagem_despachada": "2 volumes de 23kg", "marcacao_assento": "Gratuita (Assento do meio bloqueado)", "alteracao": "Sem taxa", "cancelamento": "Reembolsável 95%", "no_show": "Reembolsável"}'),

('LATAM', 'LIGHT', '{"bagagem_mao": "10kg", "bagagem_despachada": "Não inclusa", "marcacao_assento": "Paga", "alteracao": "Permitida com taxa", "cancelamento": "Não reembolsável", "no_show": "Sem reembolso"}'),
('LATAM', 'STANDARD', '{"bagagem_mao": "10kg", "bagagem_despachada": "1 volume de 23kg", "marcacao_assento": "Paga", "alteracao": "Permitida com taxa", "cancelamento": "Reembolsável 40%", "no_show": "Sem reembolso"}'),
('LATAM', 'PREMIUM_ECONOMY', '{"bagagem_mao": "10kg", "bagagem_despachada": "2 volumes de 23kg", "marcacao_assento": "Gratuita (Assento do meio bloqueado)", "alteracao": "Sem taxa", "cancelamento": "Reembolsável 95%", "no_show": "Reembolsável"}'),

('AZUL', 'AZUL', '{"bagagem_mao": "10kg", "bagagem_despachada": "Não inclusa", "marcacao_assento": "Paga", "alteracao": "Permitida com taxa", "cancelamento": "Não reembolsável", "no_show": "Sem reembolso"}'),
('AZUL', 'MAIS_AZUL', '{"bagagem_mao": "10kg", "bagagem_despachada": "1 volume de 23kg", "marcacao_assento": "Gratuita", "alteracao": "Sem taxa", "cancelamento": "Reembolsável 60%", "no_show": "Sem reembolso"}');
